const styles = (theme) => ({
  container: {
    borderRadius: "6px 0px 0px 6px",
    boxShadow: "rgba(0, 0, 0, 0.16) 0px 21px 36px",
    cursor: "pointer",
    position: "fixed",
    right: "0px",
    top: "50%",
    marginTop: "-46px",
    zIndex: 99,
    border: 0,
    outline: 0,
    backgroundColor: theme.palette.primary.main,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    [theme.breakpoints.down(510)]: {
      // marginTop: 0,
      top: 'auto',
      width: "calc(100% - 60px)",
      height: 45,
      padding: "2px 2px 2px 30px",
      bottom: 30,
      right: 30,
      borderRadius: 60,
      flexDirection: "row",
      justifyContent: "space-between",
    },
  },
  title: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 13,
    fontWeight: 700,
    color: theme.palette.primary.contrastText,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "15px 10px",
  },
  body: {
    width: "auto",
    height: "35px",
    minWidth: "80px",
    overflow: "hidden",
    borderRadius: "6px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.palette.primary.contrastText,
    fontFamily: theme.typography.fontFamily,
    fontSize: theme.typography.fontSize,
    fontWeight: theme.typography.fontWeight,
    color: theme.palette.primary.main,
    margin: "0px 10px 10px",
    [theme.breakpoints.down(510)]: {
      margin: '10px 0px',
      borderRadius: "60px",
    },
  },
});

export default styles;
