export const CHANGE_PRIMARY_COLOR = 'CHANGE_PRIMARY_COLOR';
export const CHANGE_CONTRAST_TEXT_COLOR = 'CHANGE_CONTRAST_TEXT_COLOR';
export const CHANGE_PRIMARY_TEXT_COLOR = 'CHANGE_PRIMARY_TEXT_COLOR';
export const CHANGE_SECODARY_TEXT_COLOR = 'CHANGE_SECODARY_TEXT_COLOR';
export const CHANGE_HOME_BACKGROUND_IMAGE = 'CHANGE_HOME_BACKGROUND_IMAGE';
export const CHANGE_LOGO_IMAGE = 'CHANGE_LOGO_IMAGE';
export const TOGGLE_LOG_USE_TEXT_ONLY = 'TOGGLE_LOG_USE_TEXT_ONLY';

export const CHANGE_LOGO_TEXT = 'CHANGE_LOGO_TEXT';
export const CHANGE_LOGO_TEXT_REQUEST = 'CHANGE_LOGO_TEXT_REQUEST';
