const styles = (theme) => ({
  container: {
    borderRadius: '6px 0px 0px 6px',
    // boxShadow: 'rgba(0, 0, 0, 0.16) 0px 21px 36px',
    cursor: 'pointer',
    position: 'fixed',
    right: '0px',
    top: 130,
    width: 36,
    zIndex: 999,
    border: 0,
    outline: 0,
    backgroundColor: theme.palette.primary.main,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  title: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 13,
    fontWeight: 700,
    color: theme.palette.primary.contrastText,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '15px 10px',
  },
  paper: {
    maxWidth: 520,
    position: 'fixed',
    top: 100,
    right: 50,
    zIndex: 999,
    color: theme.palette.primary.contrastText,
    border: '2px solid',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'stretch',
    padding: 8,
    backgroundColor: 'rgb(150, 255, 255)',
    borderColor: 'rgb(150, 255, 255)',
  },
  paperHide: {
    display: 'none',
  },
  sideBar: {
    width: 120,
    backgroundColor: theme.palette.background.paper,
    border: '1px solid gray',
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
  },
  subpage: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  content: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 16,
    backgroundColor: theme.palette.background.paper,
    borderRight: '1px solid gray',
    borderBottom: '1px solid gray',
    color: 'red',
    borderBottomRightRadius: 4,
    maxHeight: 400,
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    height: 50,
    backgroundColor: theme.palette.background.paper,
    border: '1px solid gray',
    borderLeft: 'none',
    borderTopRightRadius: 4,
  }
});

export default styles;