import * as productConstants from "../constants/products";
import uniqid from "uniqid";

const initialState = [
  {
    id: uniqid(),
    name: 'Apples',
    description: 'An apple is a sweet, edible fruit produced by an apple tree (Malus domestica). Apple trees are ... The skin of ripe apples is generally red, yellow, green, pink, or russetted, though many bi- or tri-colored cultivars may be found.',
    quantity: 2,
    unit: 'lb',
    price: 2,
    discountPercentage: 20,
    images: ['/images/products/Apples.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['fruits', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Baby Spinach',
    description: 'Spinach (Spinacia oleracea) is a leafy green flowering plant native to central and western Asia. It is of the order Caryophyllales, family Amaranthaceae, subfamily Chenopodioideae. Its leaves are a common edible vegetable consumed either fresh.',
    quantity: 0.2,
    unit: 'lb',
    price: 0.6,
    discountPercentage: 0,
    images: ['/images/products/BabySpinach.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['vegetables', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Celery Stick',
    description: 'celery stick - celery stalks cut into small sticks. crudites - raw vegetables cut into bite-sized strips and served with a dip. celery - stalks eaten raw or cooked or used as seasoning.',
    quantity: 1,
    unit: 'lb',
    price: 0.7,
    discountPercentage: 0,
    images: ['/images/products/CelerySticks.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['vegetables', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Sweet Corn',
    description: 'Maize, also known as corn, is a cereal grain first domesticated by indigenous peoples in southern Mexico about 10,000 years ago. The leafy stalk of the plant produces pollen inflorescences and separate ovuliferous inflorescences called ears that yield kernels or seeds, which are fruits.',
    quantity: 2.5,
    unit: 'lb',
    price: 3,
    discountPercentage: 0,
    images: ['/images/products/Corn.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['vegetables', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Cucumber',
    description: 'Cucumber is a widely cultivated plant in the gourd family, Cucurbitaceae. It is a creeping vine that bears cucumiform fruits that are used as vegetables. There are three main varieties of cucumber: slicing, pickling, and seedless. Within these varieties, several cultivars have been created.',
    quantity: 4,
    unit: 'lb',
    price: 2.2,
    discountPercentage: 0,
    images: ['/images/products/Cucumber.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['vegetables', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Dates',
    description: 'Phoenix dactylifera, commonly known as date or date palm, is a flowering plant species in the palm family, Arecaceae, cultivated for its edible sweet fruit.',
    quantity: 2,
    unit: 'lb',
    price: 15,
    discountPercentage: 20,
    images: ['/images/products/Dates.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['fruits', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'French Green Beans',
    description: 'Green beans are the unripe, young fruit and protective pods of various cultivars of the common bean. Immature or young pods of the runner bean, yardlong bean, and hyacinth bean are used in a similar way.',
    quantity: 0.6,
    unit: 'lb',
    price: 2,
    discountPercentage: 10,
    images: ['/images/products/FrenchGreenBeans.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['vegetables', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Lime',
    description: 'The lemon/lime, Citrus limon Osbeck, is a species of small evergreen tree in the flowering plant family Rutaceae, native to South Asia, primarily North eastern India.',
    quantity: 12,
    unit: 'pc(s)',
    price: 1.5,
    discountPercentage: 0,
    images: ['/images/products/GreenLimes.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['fruits', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Mango',
    description: 'A mango is a juicy stone fruit produced from numerous species of tropical trees belonging to the flowering plant genus Mangifera, cultivated mostly for their edible fruit. Most of these species are found in nature as wild mangoes. The genus belongs to the cashew family Anacardiaceae.',
    quantity: 2,
    unit: 'lb',
    price: 2.5,
    discountPercentage: 0,
    images: ['/images/products/Mangoes.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['fruits', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Pepper',
    description: 'Black pepper is a flowering vine in the family Piperaceae, cultivated for its fruit, known as a peppercorn, which is usually dried and used as a spice and seasoning. When fresh and fully mature, it is about 5 mm in diameter and dark red, and contains a single seed, like all drupes',
    quantity: 1.5,
    unit: 'lb',
    price: 10,
    discountPercentage: 20,
    images: ['/images/products/MiniPeppers.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['vegetables', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Cherry',
    description: 'A cherry is the fruit of many plants of the genus Prunus, and is a fleshy drupe. Commercial cherries are obtained from cultivars of several species, such as the sweet Prunus avium and the sour Prunus cerasus',
    quantity: 0.5,
    unit: 'lb',
    price: 2,
    discountPercentage: 0,
    images: ['/images/products/RedCherries.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['fruits', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Strawberry',
    description: 'The garden strawberry is a widely grown hybrid species of the genus Fragaria, collectively known as the strawberries, which are cultivated worldwide for their fruit. The fruit is widely appreciated for its characteristic aroma, bright red color, juicy texture, and sweetness.',
    quantity: 1,
    unit: 'lb',
    price: 5,
    discountPercentage: 50,
    images: ['/images/products/Strawberry.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['fruits', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Mix Vegetable Platter',
    description: 'Spinach (Spinacia oleracea) is a leafy green flowering plant native to central and western Asia. It is of the order Caryophyllales, family Amaranthaceae, subfamily Chenopodioideae. Its leaves are a common edible vegetable consumed either fresh.',
    quantity: 0.4,
    unit: 'lb',
    price: 1.6,
    discountPercentage: 0,
    images: ['/images/products/VeggiePlatter.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['vegetables', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Lemon',
    description: 'The lemon/lime, Citrus limon Osbeck, is a species of small evergreen tree in the flowering plant family Rutaceae, native to South Asia, primarily North eastern India.',
    quantity: 12,
    unit: 'pc(s)',
    price: 1.5,
    discountPercentage: 0,
    images: ['/images/products/Yellow_Limes.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['fruits', 'fruits-and-vegetables'],
  },
  {
    id: uniqid(),
    name: 'Belmont Custard Cream',
    description: 'A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.',
    quantity: 0.5,
    unit: 'lb',
    price: 5,
    discountPercentage: 10,
    images: ['/images/products/belmont_custard_cream.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['biscuits', 'snacks'],
  },
  {
    id: uniqid(),
    name: 'Crawford Digestives',
    description: 'A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.',
    quantity: 0.8,
    unit: 'lb',
    price: 8,
    discountPercentage: 20,
    images: ['/images/products/crawford_digestives.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['biscuits', 'snacks'],
  },
  {
    id: uniqid(),
    name: 'Crawford Shortie',
    description: 'A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.',
    quantity: 0.6,
    unit: 'lb',
    price: 5,
    discountPercentage: 0,
    images: ['/images/products/crawford_shortie.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['biscuits', 'snacks'],
  },
  {
    id: uniqid(),
    name: 'Hill Mini Pack Mix',
    description: 'A biscuit is a flour-based baked food product. This article covers the type of biscuit found in Africa, Asia, and Europe, which is typically hard, flat, and unleavened.',
    quantity: 1,
    unit: 'pc(s)',
    price: 10,
    discountPercentage: 5,
    images: ['/images/products/Hill_Biscuits_Mini_Pack_Mix_.jpg', '/images/products/Apples.jpg', '/images/products/BabySpinach.jpg'],
    categories: ['biscuits', 'snacks'],
  },
]

let newList = [];

const productReducer = (state = initialState, action) => {
  switch (action.type) {
    case productConstants.ADD_PRODUCT_ITEM:
      newList = state;
      newList.push(action.payload.product);
      return [...newList];
    case productConstants.REMOVE_PRODUCT_ITEM:
      newList = state.filter(product => product.id !== action.payload.id);
      return [...newList];
    default:
      return state;
  }
};

export default productReducer;
